Implemented basic support for new ondisk storage format 'ondisk2'
git-svn-id: https://svn.smr.arpa.emr.it/arkimet/arkimet/trunk@1153 9b5092fc-ae44-42f6-b796-0d08dad2e17b

diff --git a/arki/runtest b/arki/runtest
--- a/arki/runtest
+++ b/arki/runtest
@@ -47,12 +47,20 @@ BASE=`basename $CMD`
 if [ ! -z "$DEBUGGER" ] && [ -x $DIR/.libs/lt-$BASE ]
 then
 	echo "Running $DEBUGGER $DIR/.libs/lt-$BASE $ARGS"
-	$DEBUGGER $DIR/.libs/lt-$BASE $ARGS
-	RES=$?
+	RES=0
+	if ! $DEBUGGER $DIR/.libs/lt-$BASE $ARGS
+	then
+		RES=$?
+		echo "Failed with result $RES"
+	fi
 else
 	echo "Running $DEBUGGER $CMD $ARGS"
-	$DEBUGGER $CMD $ARGS
-	RES=$?
+	RES=0
+	if !  $DEBUGGER $CMD $ARGS
+	then
+		RES=$?
+		echo "Failed with result $RES"
+	fi
 fi
 
 
